@{
  RootModule = '.\WatchTV.psm1'
  ModuleVersion = '0.90.0'
  GUID = 'dbaa107f-646d-4ffd-9f6f-54b79131cf7a'
  Author = ''
  CompanyName = ''
  Copyright = ''
  Description = 'Extract live stream playlist URLs for various news stations.'
  FunctionsToExport = @(
    "Get-ABC7StreamUrl"
    , "Get-FCNStreamUrl"
    , "Get-KAREStreamUrl"
    , "Get-KATVStreamUrl"
    , "Get-KCBSStreamUrl"
    , "Get-KCDOStreamUrl"
    , "Get-KCNCStreamUrl"
    , "Get-KCTVStreamUrl"
    , "Get-KDKAStreamUrl"
    , "Get-KENSStreamUrl"
    , "Get-KFMBStreamUrl"
    , "Get-KFORStreamUrl"
    , "Get-KGTVStreamUrl"
    , "Get-KIONStreamUrl"
    , "Get-KJRHStreamUrl"
    , "Get-KMOVStreamUrl"
    , "Get-KMPHStreamUrl"
    , "Get-KMSPStreamUrl"
    , "Get-KMTVStreamUrl"
    , "Get-KNBCStreamUrl"
    , "Get-KNSDStreamUrl"
    , "Get-KNTVStreamUrl"
    , "Get-KNXVStreamUrl"
    , "Get-KOCOStreamUrl"
    , "Get-KOTVStreamUrl"
    , "Get-KOVRStreamUrl"
    , "Get-KPIXStreamUrl"
    , "Get-KPNXStreamUrl"
    , "Get-KPRCStreamUrl"
    , "Get-KPTVStreamUrl"
    , "Get-KRGVStreamUrl"
    , "Get-KSATStreamUrl"
    , "Get-KSAZStreamUrl"
    , "Get-KSBWStreamUrl"
    , "Get-KSHBStreamUrl"
    , "Get-KSTUStreamUrl"
    , "Get-KSWBStreamUrl"
    , "Get-KTABStreamUrl"
    , "Get-KTAZStreamUrl"
    , "Get-KTTVStreamUrl"
    , "Get-KTSMStreamUrl"
    , "Get-KTVHStreamUrl"
    , "Get-KTVTStreamUrl"
    , "Get-KUSIStreamUrl"
    , "Get-KVEAStreamUrl"
    , "Get-KWTVStreamUrl"
    , "Get-KXANStreamUrl"
    , "Get-KXASStreamUrl"
    , "Get-KYWStreamUrl"
    , "Get-WAGAtreamUrl"
    , "Get-WALAStreamUrl"
    , "Get-WAPTStreamUrl"
    , "Get-WBALStreamUrl"
    , "Get-WBBMStreamUrl"
    , "Get-WBFFStreamUrl"
    , "Get-WBIRStreamUrl"
    , "Get-WBRCStreamUrl"
    , "Get-WBTSStreamUrl"
    , "Get-WBZStreamUrl"
    , "Get-WCAUStreamUrl"
    , "Get-WCAXStreamUrl"
    , "Get-WCBSStreamUrl"
    , "Get-WCCBStreamUrl"
    , "Get-WCCOStreamUrl"
    , "Get-WCVBStreamUrl"
    , "Get-WDCWStreamUrl"
    , "Get-WESHStreamUrl"
    , "Get-WFLA38StreamUrl"
    , "Get-WFLAStreamUrl"
    , "Get-WFMJStreamUrl"
    , "Get-WFORStreamUrl"
    , "Get-WFSBStreamUrl"
    , "Get-WFTXStreamUrl"
    , "Get-WHASStreamUrl"
    , "Get-WHIOStreamUrl"
    , "Get-WJARStreamUrl"
    , "Get-WJLAStreamUrl"
    , "Get-WJXTStreamUrl"
    , "Get-WJYZStreamUrl"
    , "Get-WJZStreamUrl"
    , "Get-WKBWStreamUrl"
    , "Get-WLWTStreamUrl"
    , "Get-WMAQStreamUrl"
    , "Get-WNBCStreamUrl"
    , "Get-WNEUStreamUrl"
    , "Get-WOODStreamUrl"
    , "Get-WPHLStreamUrl"
    , "Get-WPIXStreamUrl"
    , "Get-WPMTStreamUrl"
    , "Get-WPRIStreamUrl"
    , "Get-WPTVStreamUrl"
    , "Get-WSVNStreamUrl"
    , "Get-WRCStreamUrl"
    , "Get-WTAEStreamUrl"
    , "Get-WTHRStreamUrl"
    , "Get-WTKRStreamUrl"
    , "Get-WTOCStreamUrl"
    , "Get-WTVFStreamUrl"
    , "Get-WTVJStreamUrl"
    , "Get-WTVTStreamUrl"
    , "Get-WVITStreamUrl"
    , "Get-WWJStreamUrl"
    , "Get-WXMIStreamUrl"
    , "Get-WXYZStreamUrl"
    , "Get-WYFFStreamUrl"
    , "Get-WZTVStreamUrl"
    , "Get-WZVNStreamUrl"
    , "Get-XEWTStreamUrl"
    , "Get-XHABStreamUrl"
    , "Get-XHGStreamUrl"

    , "Get-CTVTorontoDVR"
    , "Get-TegnaDVR"
    , "Get-NewsONDVR"
    , "Get-FCNDVR"
    , "Get-KAREDVR"
    , "Get-KCENDVR"
    , "Get-KFMBDVR"
    , "Get-KIIIDVR"
    , "Get-KINGDVR"
    , "Get-KPNXDVR"
    , "Get-KVOADVR"
    , "Get-KVUEDVR"
    , "Get-KYTXDVR"
    , "Get-WFAADVR"
    , "Get-WFMYDVR"
    , "Get-WFTXDVR"
    , "Get-WHASDVR"
    , "Get-WJZDVR"
    , "Get-WNEPDVR"
    , "Get-WPMTDVR"
    , "Get-WPTVDVR"
    , "Get-WTHRDVR"
    , "Get-WTSPDVR"
    , "Get-WTVFDVR"
    , "Get-WUSADVR"
    , "Get-WWLDVR"
    , "Get-WXIADVR"
    , "Get-WXMIDVR"
    , "Get-WZZMDVR"

    , "Get-CNBCStreamUrl"

    , "Get-UA"
    , "Get-CabletownStreamUrl"
    , "Get-EyemarkStreamUrl"
    , "Get-FoxStreamUrl"
    , "Get-GenericStreamUrl"
    , "Get-GMGStreamUrl"
    , "Get-GrayStreamUrl"
    , "Get-GrayStreamInfo"
    , "Get-HearstStreamUrl"
    , "Get-NexstarStreamUrl"
    , "Get-SinclairStreamUrl"
    , "Get-YouTubeLiveIds"
    , "Get-NewsONStations"
    , "Get-ZeamDVRInfo"
    , "Get-ZeamStreamUrl"
  )
  CmdletsToExport = @()
  VariablesToExport = '*'
  AliasesToExport = '*'
  PrivateData = @{
    PSData = @{
      LicenseUri = 'https://opensource.org/licenses/0BSD'
    }
  }
}
